### ISSUE TITLE
Ensemble spread-skill plot doesn't correctly read in MET ensemble spread skill file

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplotpy#271]
## Describe the Problem ##
When attempting to read in an ensemble stat ASCII file, the ens_ss.py file raises an error about the bin_n key.  It is expecting a column header of 'bin_n', but in the ASCII file generated by MET, the header is 'BIN_N'.  

### Expected Behavior ###

You will generate a similar error message when attempting to use the ens_ss ASCII file as input to the METplotpy ens_ss.py plot:

> Traceback (most recent call last):
>   File "/Users/minnawin/miniconda/envs/mac_metplotpy_py38/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
>     return self._engine.get_loc(casted_key)
>   File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
>   File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
> KeyError: 'bin_n'
> 
> 
> Traceback (most recent call last):
>   File "ens_ss.py", line 552, in <module>
>     main()
>   File "ens_ss.py", line 542, in main
>     plot = EnsSs(docs)
>   File "ens_ss.py", line 76, in __init__
>     self._perform_event_equalization()
>   File "ens_ss.py", line 109, in _perform_event_equalization
>     unique_bin_n = self.input_df['bin_n'].unique().tolist()
>   File "/Users/minnawin/miniconda/envs/mac_metplotpy_py38/lib/python3.8/site-packages/pandas/core/frame.py", line 3505, in __getitem__
>     indexer = self.columns.get_loc(key)
>   File "/Users/minnawin/miniconda/envs/mac_metplotpy_py38/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
>     raise KeyError(key) from err
> KeyError: 'bin_n'
> 
> 
> 

### Environment ###
Describe your runtime environment:
*1. Machine: (e.g. HPC name, Linux Workstation, Mac Laptop)* Mac Laptop
*2. OS: (e.g. RedHat Linux, MacOS)* MacOS
*3. Software version number(s)* METplotpy develop METcalcpy develop (post beta3 release)

### To Reproduce ###
Describe the steps to reproduce the behavior:
Using this ASCII output from the MET ensemble stat file:

ensemble_stat_20100101_120000V_ssvar.txt
[ensemble_stat_20100101_120000V_ssvar.txt](https://github.com/dtcenter/METplotpy/files/9710724/ensemble_stat_20100101_120000V_ssvar.txt)

and the following yaml configuration file:
[custom_ens_ss.yaml.txt](https://github.com/dtcenter/METplotpy/files/9710734/custom_ens_ss.yaml.txt)

1)  Using the develop branches of METcalcpy and METplotpy, set the PYTHONPATH to point to where you downloaded the source code for these tools.  
2) Copy the ensemble_stat_20100101_120000V_ssvar.txt and custom_ens_ss.yaml.txt files to the METplotpy/metplotpy/plots/enss directory
3) Rename the custom_ens_ss.yaml.txt  to custom_ens_ss.yaml
4) Run the following: python enss.py ./custom_ens_ss.yaml

You will generate a similar error message:
Traceback (most recent call last):
  File "/Users/minnawin/miniconda/envs/mac_metplotpy_py38/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'bin_n'

Traceback (most recent call last):
  File "ens_ss.py", line 552, in <module>
    main()
  File "ens_ss.py", line 542, in main
    plot = EnsSs(docs)
  File "ens_ss.py", line 76, in __init__
    self._perform_event_equalization()
  File "ens_ss.py", line 109, in _perform_event_equalization
    unique_bin_n = self.input_df['bin_n'].unique().tolist()
  File "/Users/minnawin/miniconda/envs/mac_metplotpy_py38/lib/python3.8/site-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/minnawin/miniconda/envs/mac_metplotpy_py38/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'bin_n'

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2792542

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Organization** level **Project** for support of the current coordinated release
- [ ] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

**Comment by bikegeek** [comment]
in ens_ss.py, running the debugger indicates that the pandas dataframe is reading in the column headers in all caps (i.e. BIN_N, BIN_I, VERSION, MODEL, FCST_VALID_END, etc.). This error is first appearing in the event equalization code, but when event equalization is turned off (setting set to False),  another KeyError is raised: 
KeyError: 'model' with the following stack trace:

Traceback (most recent call last):
  File "../../metplotpy/plots/ens_ss/ens_ss.py", line 552, in <module>
    main()
  File "../../metplotpy/plots/ens_ss/ens_ss.py", line 542, in main
    plot = EnsSs(docs)
  File "../../metplotpy/plots/ens_ss/ens_ss.py", line 82, in __init__
    self.series_list = self._create_series(self.input_df)
  File "../../metplotpy/plots/ens_ss/ens_ss.py", line 187, in _create_series
    series_obj = EnsSsSeries(self.config_obj, i, input_data, series_list, name)
  File "/Volumes/d1/minnawin/bugfix_271_ens_ss/METplotpy/metplotpy/plots/ens_ss/ens_ss_series.py", line 39, in __init__
    super().__init__(config, idx, input_data, y_axis)
  File "/Volumes/d1/minnawin/bugfix_271_ens_ss/METplotpy/metplotpy/plots/series.py", line 69, in __init__
    self.series_points = self._create_series_points()
  File "/Volumes/d1/minnawin/bugfix_271_ens_ss/METplotpy/metplotpy/plots/ens_ss/ens_ss_series.py", line 92, in _create_series_points
    all_filters.append((self.input_data[field].isin(filter_list)))
  File "/Users/minnawin/miniconda/envs/mac_metplotpy_py38/lib/python3.8/site-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/minnawin/miniconda/envs/mac_metplotpy_py38/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'model'


Replacing model with MODEL in the configuration file for the series_val_1 setting results in the same type or error, except: KeyError: 'MODEL', so this *DOES NOT* appear to be a *SIMPLE* issue of all caps vs lower case column headers in the data.

**Comment by bikegeek** [comment]
comparing the dataframes from the original dataset ens_ss.data vs ensemble_stat_20100101_120000V_ssvar.txt indicates that the formatting of the ASCII text files has an impact on the pandas dataframe that is created.  For the original data, using pd.read_csv(self.config_obj.parameters['stat_input'], sep='\t', header='infer', float_precision='round_trip') will result in a very different pandas dataframe when applied to the ensemble_stat_20100101_V120000V_ssvar.txt data.

**Comment by bikegeek** [comment]
Here is the work-around to supporting tab or whitespace input data in the ens_ss.py code for reading in the data:

        with open(self.config_obj.parameters['stat_input']) as stat_file:
            header = stat_file.readline()
            result = re.split('\t', header)
            if len(result) > 1:
                    return pd.read_csv(self.config_obj.parameters['stat_input'], sep="\t",
                                   header='infer', engine='python')
            else:
                return pd.read_csv(self.config_obj.parameters['stat_input'], sep="\s+",
                       header='infer', engine='python')

**Comment by bikegeek** [comment]
Closing this issue, as it will be rectified by this issue:
Please see Github Issue https://github.com/dtcenter/METdataio/issues/121

This will address the underlying cause of the issue, which is the difference in the MET format with that of the files generated by METviewer (which is what the plots in METplotpy are expecting)
