### ISSUE TITLE
TC-RMW plot needs updating to support changes to input

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplotpy#425]
## Describe the Problem ##
When using updated TC-RMW data, the METplotpy TC-RMW plot for the cross-section is raising errors like the following:
TypeError Length of x(100) must match number of columns in z(3) and other similar dimension mismatch TypeError messages.

Changes to the order of the dimensions in  https://github.com/dtcenter/METcalcpy/issues/308
are not supposed to impact the contour plot, but the contour plot is sensitive to this.

### Environment ###
Describe your runtime environment:
*1. Machine: (e.g. HPC name, Linux Workstation, Mac Laptop)*
*2. OS: (e.g. RedHat Linux, MacOS)*
*3. Software version number(s)*

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. Go to '...'*
*2. Click on '....'*
*3. Scroll down to '....'*
*4. See error*
*Post relevant sample data following these instructions:*
*https://dtcenter.org/community-code/model-evaluation-tools-met/met-help-desk#ftp*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Organization** level **Project** for support of the current coordinated release
- [ ] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED CYCLE ASSIGNMENT** label
- [ ] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

**Comment by bikegeek** [comment]
Two changes need to be made in the **_plot_cross_section.py_** code:

- when calculating the field_azi_mean, set axis=0 instead of 1

- for the Z value in the contour plot, use the field_azi_mean rather than the field_azi_mean.transpose to get the correct dimensions for the contour plot.

**Comment by bikegeek** [comment]
Instructions for performing the vertical interpolation and generating the cross-plot on 'seneca':
[README.txt](https://github.com/dtcenter/METplotpy/files/14502759/README.txt)

**Comment by mrinalbiswas** [comment]
I have tested the changes on seneca and it ran successfully.

**Comment by mkavulich** [comment]
I appear to be dealing with this same issue...I am trying to run some tests with METcalcpy and METplotpy v2.1, and even while following the above instructions to modify plot_cross_section.py I get an exception in `matplotlib` when trying to save the figure:

```
/scratch2/BMC/fv3lam/kavulich/vanderlei_plotting/metcalcpy_test$ python plot_cross_section.py --datadir . --plotdir . --filename tc_rmw_dev_test_vertical_interp.nc --config plot_cross_section.yaml
Traceback (most recent call last):
  File "/scratch2/BMC/fv3lam/kavulich/vanderlei_plotting/metcalcpy_test/plot_cross_section.py", line 109, in <module>
    plot_cross_section(plotting_config, input_data, input_args)
  File "/scratch2/BMC/fv3lam/kavulich/vanderlei_plotting/metcalcpy_test/plot_cross_section.py", line 76, in plot_cross_section
    fig.savefig(os.path.join(plot_outdir, config['plot_filename'] + '.png'), dpi=config['plot_res'])
  File "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.8.0-dtc-met/envs/ue-intel-2021.5.0/install/intel/2021.5.0/py-matplotlib-3.7.4-wc6m4ku/lib/python3.11/site-packages/matplotlib/figure.py", line 3378, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.8.0-dtc-met/envs/ue-intel-2021.5.0/install/intel/2021.5.0/py-matplotlib-3.7.4-wc6m4ku/lib/python3.11/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    result = print_method(
             ^^^^^^^^^^^^^
  File "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.8.0-dtc-met/envs/ue-intel-2021.5.0/install/intel/2021.5.0/py-matplotlib-3.7.4-wc6m4ku/lib/python3.11/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
                                                                 ^^^^^
  File "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.8.0-dtc-met/envs/ue-intel-2021.5.0/install/intel/2021.5.0/py-matplotlib-3.7.4-wc6m4ku/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.8.0-dtc-met/envs/ue-intel-2021.5.0/install/intel/2021.5.0/py-matplotlib-3.7.4-wc6m4ku/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py", line 457, in _print_pil
    FigureCanvasAgg.draw(self)
  File "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.8.0-dtc-met/envs/ue-intel-2021.5.0/install/intel/2021.5.0/py-matplotlib-3.7.4-wc6m4ku/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py", line 400, in draw
    self.figure.draw(self.renderer)
  File "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.8.0-dtc-met/envs/ue-intel-2021.5.0/install/intel/2021.5.0/py-matplotlib-3.7.4-wc6m4ku/lib/python3.11/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.8.0-dtc-met/envs/ue-intel-2021.5.0/install/intel/2021.5.0/py-matplotlib-3.7.4-wc6m4ku/lib/python3.11/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.8.0-dtc-met/envs/ue-intel-2021.5.0/install/intel/2021.5.0/py-matplotlib-3.7.4-wc6m4ku/lib/python3.11/site-packages/matplotlib/figure.py", line 3175, in draw
    mimage._draw_list_compositing_images(
  File "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.8.0-dtc-met/envs/ue-intel-2021.5.0/install/intel/2021.5.0/py-matplotlib-3.7.4-wc6m4ku/lib/python3.11/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.8.0-dtc-met/envs/ue-intel-2021.5.0/install/intel/2021.5.0/py-matplotlib-3.7.4-wc6m4ku/lib/python3.11/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.8.0-dtc-met/envs/ue-intel-2021.5.0/install/intel/2021.5.0/py-matplotlib-3.7.4-wc6m4ku/lib/python3.11/site-packages/matplotlib/axes/_base.py", line 3028, in draw
    self._update_title_position(renderer)
  File "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.8.0-dtc-met/envs/ue-intel-2021.5.0/install/intel/2021.5.0/py-matplotlib-3.7.4-wc6m4ku/lib/python3.11/site-packages/matplotlib/axes/_base.py", line 2972, in _update_title_position
    ax.yaxis.get_tightbbox(renderer)  # update offsetText
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.8.0-dtc-met/envs/ue-intel-2021.5.0/install/intel/2021.5.0/py-matplotlib-3.7.4-wc6m4ku/lib/python3.11/site-packages/matplotlib/axis.py", line 1335, in get_tightbbox
    ticks_to_draw = self._update_ticks()
                    ^^^^^^^^^^^^^^^^^^^^
  File "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.8.0-dtc-met/envs/ue-intel-2021.5.0/install/intel/2021.5.0/py-matplotlib-3.7.4-wc6m4ku/lib/python3.11/site-packages/matplotlib/axis.py", line 1274, in _update_ticks
    major_locs = self.get_majorticklocs()
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.8.0-dtc-met/envs/ue-intel-2021.5.0/install/intel/2021.5.0/py-matplotlib-3.7.4-wc6m4ku/lib/python3.11/site-packages/matplotlib/axis.py", line 1496, in get_majorticklocs
    return self.major.locator()
           ^^^^^^^^^^^^^^^^^^^^
  File "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.8.0-dtc-met/envs/ue-intel-2021.5.0/install/intel/2021.5.0/py-matplotlib-3.7.4-wc6m4ku/lib/python3.11/site-packages/matplotlib/ticker.py", line 2136, in __call__
    return self.tick_values(vmin, vmax)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.8.0-dtc-met/envs/ue-intel-2021.5.0/install/intel/2021.5.0/py-matplotlib-3.7.4-wc6m4ku/lib/python3.11/site-packages/matplotlib/ticker.py", line 2144, in tick_values
    locs = self._raw_ticks(vmin, vmax)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.8.0-dtc-met/envs/ue-intel-2021.5.0/install/intel/2021.5.0/py-matplotlib-3.7.4-wc6m4ku/lib/python3.11/site-packages/matplotlib/ticker.py", line 2083, in _raw_ticks
    nbins = np.clip(self.axis.get_tick_space(),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.8.0-dtc-met/envs/ue-intel-2021.5.0/install/intel/2021.5.0/py-matplotlib-3.7.4-wc6m4ku/lib/python3.11/site-packages/matplotlib/axis.py", line 2789, in get_tick_space
    return int(np.floor(length / size))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot convert float NaN to integer
```

The reason I'm running an older version of these tools is I'm trying to verify an installation was made correctly on Hera. So it's possible that this is a problem with the installation I'm working with and not METplotpy, but I'm curious if any of the MET folks have any thoughts.

**Comment by bikegeek** [comment]
I see you are using python 3.11 and matplotlib 3.7.4, we are only
supporting python 3.10, and matplotlib 3.6.3.  Is there any way you can
test things out on a host that has the required versions as specified in
the requirements.txt file in:
https://github.com/dtcenter/METplotpy/blob/main_v3.0/requirements.txt

Regards,
Minna

**Comment by mkavulich** [comment]
This is an attempted install in the context of spack-stack (see https://github.com/JCSDA/spack-stack/issues/1112), so those higher versions are requirements of other components of the stack. Unfortunately I don't think it'll be possible to downgrade.

I did take a look at the data and it appears as if there are NaNs in the input data...is this expected? Or maybe something went wrong at the METcalcpy step?

**Comment by bikegeek** [comment]
Can you put the input data on 'seneca'?  What are you using METcalcpy for?

Regards,
Minna

**Comment by mkavulich** [comment]
Right now, I am running the example cases given in the Users Guide

METcalcpy: https://metcalcpy.readthedocs.io/en/main_v2.1/Users_Guide/vertical_interpolation.html#example
METplotpy: https://metplotpy.readthedocs.io/en/main_v2.1/Users_Guide/tcrmw_cross_section.html#example

The METcalcpy step appeared to be successful, but as I said, I have now discovered there are `NaN` output values, which I don't know if that is expected or not.

I am not sure if I have access to seneca, is this a machine you need to apply for access to? I can put the data on Derecho if that would work.

**Comment by bikegeek** [comment]
If you are using the data from the Users Guide, I'll try and track it down
and try out some things on 'seneca'.  I have a release coming up
(tomorrow), so I might not have any insight before then.

Regards,
Minna
